### Iterating NumPy Arrays

In [1]:
import numpy as np

In [3]:
# 1D Array
var1 = np.array([1,2,3,4,5,6,7,8,9,10])
print(var1)
print()
for i in var1:
    print(i,end=' ')

[ 1  2  3  4  5  6  7  8  9 10]

1 2 3 4 5 6 7 8 9 10 

In [8]:
var2 = np.array([[1,2,3,4],[5,6,7,8]])
print(var2)

print()

for i in var2:
    print(i)

print()

for i in var2:
    for j in i:
        print(j,end=' ')

[[1 2 3 4]
 [5 6 7 8]]

[1 2 3 4]
[5 6 7 8]

1 2 3 4 5 6 7 8 

In [15]:
# 3D Array
var3 = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
print(var3)

print()
print("1 loop")

for i in var3:
    print(i)
    
print()
print('2 loop')

for i in var3:
    for j in i:
        print(j)
        
print()
print('3 loop')
for i in var3:
    for j in i:
        for k in j:
            print(k,end=' ')

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]

1 loop
[[1 2 3 4]
 [5 6 7 8]]
[[ 9 10 11 12]
 [13 14 15 16]]

2 loop
[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]
[13 14 15 16]

3 loop
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 

In [16]:
# skipping the 3 loop using (nditer)
for i in np.nditer(var3):
    print(i,end=' ')

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 

In [17]:
# changing values using some special attributes of nditer
for i in np.nditer(var3,flags=['buffered'],op_dtypes=['S']):
    print(i)

b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'
b'8'
b'9'
b'10'
b'11'
b'12'
b'13'
b'14'
b'15'
b'16'


In [18]:
# Data with Index number
for i,d in np.ndenumerate(var3):
    print(f'At Index {i} Data is {d}')

At Index (0, 0, 0) Data is 1
At Index (0, 0, 1) Data is 2
At Index (0, 0, 2) Data is 3
At Index (0, 0, 3) Data is 4
At Index (0, 1, 0) Data is 5
At Index (0, 1, 1) Data is 6
At Index (0, 1, 2) Data is 7
At Index (0, 1, 3) Data is 8
At Index (1, 0, 0) Data is 9
At Index (1, 0, 1) Data is 10
At Index (1, 0, 2) Data is 11
At Index (1, 0, 3) Data is 12
At Index (1, 1, 0) Data is 13
At Index (1, 1, 1) Data is 14
At Index (1, 1, 2) Data is 15
At Index (1, 1, 3) Data is 16
