## Insert

In [1]:
import numpy as np

In [2]:
var1 = np.array([1,2,3,4])
print(var1)

[1 2 3 4]


In [4]:
print(type(var1))
print(var1.dtype)

<class 'numpy.ndarray'>
int32


In [6]:
# insert
# 3 parameters = array_name,position,value
var2 = np.insert(var1,2,40)
print(var2)

[ 1  2 40  3  4]


In [7]:
# another example
var3 = np.insert(var1, (3,4),45)
print(var3)

[ 1  2  3 45  4 45]


In [9]:
# it do not assign float value (skips the float part of value)
var4 = np.insert(var1,4,41.23)
print(var4)

[ 1  2  3  4 41]


In [11]:
# inserting in 2D array
var5 = np.array([[1,2,3],[4,5,6]])
var6 = np.insert(var5,2,9,axis=0)
print(var6)

[[1 2 3]
 [4 5 6]
 [9 9 9]]


In [12]:
var7 = np.insert(var5,2,9,axis=1)
print(var7)

[[1 2 9 3]
 [4 5 9 6]]


In [13]:
# another example
var8 = np.insert(var5,2,[22,23],axis=1)
print(var8)

[[ 1  2 22  3]
 [ 4  5 23  6]]


In [14]:
# append is also used to insert data 
# it appends the value at last
var9 = np.array([1,2,3,4])
var10 = np.append(var9, 7.2)
print(var10)

[1.  2.  3.  4.  7.2]


In [16]:
# using append in 2D array
var11 = np.array([[1,2,3],[4,5,6]])
var12 = np.append(var11,[[7,8,9]],axis=0)
print(var12)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Delete

In [17]:
# 2 args = variable_name, index_position
var13 = np.array([1,2,3,4,5,6,7,8,9,10])
var14 = np.delete(var13,6)
print(var14)

[ 1  2  3  4  5  6  8  9 10]


In [19]:
# deleting in 2D array
var15 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
var16 = np.delete(var15,(1,3))
print(var16)

[ 1  3  5  6  7  8  9 10]
