### Creating a Matrix in NumPy Array

In [1]:
import numpy as np

In [4]:
var1 = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(var1)
print(type(var1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.matrix'>


In [5]:
# it may look same as array
# the difference is in its data type
var2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(var2)
print(type(var2))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


- in matrix addition and subtraction are same as array add,sub
- but in matrix multiplication occurs using dot multiplication

In [11]:
var3 = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
var4 = np.matrix([[10,11,12],[13,14,15],[16,17,18]])
var5 = var3+var4
print(var5)

[[11 13 15]
 [17 19 21]
 [23 25 27]]


In [12]:
var6 = var4-var3
print(var6)

[[9 9 9]
 [9 9 9]
 [9 9 9]]


In [13]:
# multiplication gives error because dimension of gives example
# are not same
var7 = np.matrix([[1,2,3],[4,5,6]])
var8 = np.matrix([[7,8,9],[10,11,12]])
print(var7*var8)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [17]:
# using dot multiplication
var9 = np.matrix([[1,2],[3,4]])
var10 = np.matrix([[5,6],[7,8]])
var11 = var9.dot(var10)
print(var11)

[[19 22]
 [43 50]]


In [18]:
# simple multiplication
print(var9*var10)

[[19 22]
 [43 50]]
