# Shape

In [1]:
import numpy as np

In [ ]:
# var = np.array([[1,2,3],[4,7,8]])
print(var)
print()
print(var.shape)

In [3]:
var2 = np.array([1,2,3,4],ndmin=4)
print(var2)
print(var2.ndim)
print()
print(var2.shape)

[[[[1 2 3 4]]]]
4

(1, 1, 1, 4)


# Reshape

In [7]:
var3 = np.array([1,2,3,4,5,6])
x = var3.reshape(3,2)
print(f'No of Dimension: {var3.ndim}')
print(var3)
print()
print(f'No of Dimension: {x.ndim}')
print(x)

No of Dimension: 1
[1 2 3 4 5 6]

No of Dimension: 2
[[1 2]
 [3 4]
 [5 6]]


In [9]:
# converting to 3D array
var4 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(f'No of Dimension: {var4.ndim}')
print(var4)

print()

var5 = var4.reshape(2,3,2)
print(f'No of Dimension: {var5.ndim}')
print(var5)

No of Dimension: 1
[ 1  2  3  4  5  6  7  8  9 10 11 12]

No of Dimension: 3
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [10]:
# converting back to 1D array (we use -1 for that)
var6 = var5.reshape(-1)
print(f'No of Dimensions: {var6.ndim}')
print(var6)

No of Dimensions: 1
[ 1  2  3  4  5  6  7  8  9 10 11 12]
