### Arithmetic Operations
- a+b  =>  np.add(a,b)
- a-b  =>  np.subtract(a,b)
- a*b  =>  np.multiply(a,b)
- a/b  =>  np.divide(a,b)
- a%b  =>  np.mod(a,b)
- a**b  => np.pow(a,b)
- 1/a  => np.reciprocal(a)

In [1]:
import numpy as np

In [2]:
# adding
var = np.array([1,2,3,4])

#it will add 3 to every item of array
varadd = var+3
print(varadd)

[4 5 6 7]


In [3]:
# adding
var1 = np.array([4,5,6,7])
var2 = np.array([4,5,6,7])
var3 = var1 + var2
print(var3)

[ 8 10 12 14]


In [4]:
# subtraction
var6 = np.array([1,2,3,4])
var7 = var6 - 5
print(var7)

[-4 -3 -2 -1]


In [5]:
# multiplication
var8 = np.array([1,2,3,4])
var9 = var8 * 7
print(var9)

[ 7 14 21 28]


In [6]:
# divide
var10 = np.array([2,4,5,9])
var11 = var10/7
print(var11)

[0.28571429 0.57142857 0.71428571 1.28571429]


In [7]:
# modulas
var12 = np.array([7,8,9,11])
var13 = var12%6
print(var13)

[1 2 3 5]


### using functions

In [17]:
# adding
var14 = np.array([7,8,9,11])
var15 = np.array([6,4,5,9])
var16 = np.add(var14,var15)
print(var16)

[13 12 14 20]


In [18]:
# another way
var17 = np.add(var14,8)
print(var17)

[15 16 17 19]


In [19]:
# subtraction
var18 = np.subtract(var14,3)
print(var18)

[4 5 6 8]


In [20]:
# multiplication
var19 = np.multiply(var14,7)
print(var19)

[49 56 63 77]


In [21]:
# divide
var20 = np.divide(var14,3)
print(var20)

[2.33333333 2.66666667 3.         3.66666667]


In [22]:
# mod
var21 = np.mod(var14,4)
print(var21)

[3 0 1 3]


In [23]:
# power
var22 = np.power(var14,3)
print(var22)

[ 343  512  729 1331]


In [24]:
# reciprocal
var23 = np.reciprocal(var14)
print(var23)

[0 0 0 0]


### 2D array

In [29]:
var24 = np.array([[1,2,3,4],[5,6,7,8]])
var25 = np.array([[9,10,11,12],[13,14,15,16]])
print(var24)
print("+")
print(var25)
print("------------------")
var26 = var24+var25
print(var26)

[[1 2 3 4]
 [5 6 7 8]]
+
[[ 9 10 11 12]
 [13 14 15 16]]
------------------
[[10 12 14 16]
 [18 20 22 24]]


In [32]:
var27 = np.array([[1,2,3,4],[5,6,7,8]])
var28 = np.array([[9,10,11,12],[13,14,15,16]])
print(var27)
print("-")
print(var28)
print("------------------")
var29 = var27-var28
print(var29)

[[1 2 3 4]
 [5 6 7 8]]
-
[[ 9 10 11 12]
 [13 14 15 16]]
------------------
[[-8 -8 -8 -8]
 [-8 -8 -8 -8]]


In [34]:
var30 = np.array([[1,2,3,4],[5,6,7,8]])
var31 = np.array([[9,10,11,12],[13,14,15,16]])
print(var30)
print("*")
print(var31)
print("------------------")
var32 = var30*var31
print(var32)

[[1 2 3 4]
 [5 6 7 8]]
*
[[ 9 10 11 12]
 [13 14 15 16]]
------------------
[[  9  20  33  48]
 [ 65  84 105 128]]


In [35]:
var33 = np.array([[1,2,3,4],[5,6,7,8]])
var34 = np.array([[9,10,11,12],[13,14,15,16]])
print(var33)
print("/")
print(var34)
print("------------------")
var35 = var33*var34
print(var35)

[[1 2 3 4]
 [5 6 7 8]]
/
[[ 9 10 11 12]
 [13 14 15 16]]
------------------
[[  9  20  33  48]
 [ 65  84 105 128]]


In [36]:
var36 = np.array([[1,2,3,4],[5,6,7,8]])
var37 = np.array([[9,10,11,12],[13,14,15,16]])
print(var36)
print("%")
print(var37)
print("------------------")
var38 = var36*var37
print(var38)

[[1 2 3 4]
 [5 6 7 8]]
%
[[ 9 10 11 12]
 [13 14 15 16]]
------------------
[[  9  20  33  48]
 [ 65  84 105 128]]


In [37]:
var39 = np.array([[1,2,3,4],[5,6,7,8]])
var40 = np.array([[9,10,11,12],[13,14,15,16]])
print(var39)
print("**")
print(var40)
print("------------------")
var41 = var39**var40
print(var41)

[[1 2 3 4]
 [5 6 7 8]]
**
[[ 9 10 11 12]
 [13 14 15 16]]
------------------
[[         1       1024     177147   16777216]
 [1220703125 1054752768 1622647863          0]]


### some other Arithmetic Functions
- np.min(x)
- np.max(x)
- np.argmin(x) = gives the index of minimun
- np.argmax(x) = gives the index of maximum
- np.sqrt(x)
- np.sin(x)
- np.cos(x)
- np.cumsum(x) => gives sums using previous elements

In [38]:
var42 = np.array([1,2,3,4,5,8,44,1,3,7,21,45,93,62,78,23])
print(f'min: {np.min(var42)} at index {np.argmin(var14)}')
print(f'max: {np.max(var42)} at index {np.argmax(var14)}')

min: 1 at index 0
max: 93 at index 3


In [40]:
# according to axis
# for 2D
# axis = 0 (for column)
# axis = 1 (for row)
var43 = np.array([[4,5,1,8],[7,3,2,9],[7,4,1,3]])
print(f'min: {np.min(var43, axis=0)} according to column')
print(f'min: {np.min(var43, axis=1)} according to row')

min: [4 3 1 3] according to column
min: [1 2 1] according to row


In [41]:
print(f'max: {np.max(var43, axis=0)} according to column')
print(f'max: {np.max(var43, axis=1)} according to row')

max: [7 5 2 9] according to column
max: [8 9 7] according to row


In [42]:
# square root
print(f'square root: {np.sqrt(var43)}')

square root: [[2.         2.23606798 1.         2.82842712]
 [2.64575131 1.73205081 1.41421356 3.        ]
 [2.64575131 2.         1.         1.73205081]]


In [45]:
# sin
# cos
var44 = np.array([1,2,3,4,5])
print(np.sin(var44))
print(np.cos(var44))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]


In [46]:
# cumsum
var45 = np.array([1,2,3,4,5,6,7,8,9,10])
print(f'cumsum {np.cumsum(var45)}')

cumsum [ 1  3  6 10 15 21 28 36 45 55]
